dataset_path : "khalidrizki/indonesian-wiki-chunked-180tok"
query_col : None
ans_col : None
psg_col : 'text'
max_samples : null

# model config
model_dtype : 'bfloat16'

seed: 42
per_device_train_batch_size: 12
gradient_accumulation_steps: 4
lr_scheduler_type: "linear"
warmup_ratio: 0.03
alpha_nll: 1.0

# retriever config
retriever_name_or_path: "intfloat/multilingual-e5-large"
retrieval_context_length: 180

# prompting config
chat_format: "qwen"

# output
model_size: "1.7B"
output_dir: "../output"

# xrag
update_projector_only: true
save_embeddings_generated: false
processing_steps_output_dir: "../../generated_data/xRAG-process"
    
# task config
task_type: 'pretrain'
model_name_or_path : "Qwen/Qwen3-1.7B"
num_train_epochs : 1
learning_rate : 6.0e-3
alpha_kl : None
kl_temperature : 0.0
max_seq_length : 336
retrieval_embed_length : 1
